### ISSUE TITLE
always new window

### ISSUE THREAD

**Issue by Kikju** [musically-ut/key-ncognito#2]
When I was opening few link in incognito, it'll always open new windows. Would be possible open new tab in incognito windows?

**Comment by musically-ut** [comment]
Good idea.

I just checked and it is possible only if this extension is enabled in Incognito mode: https://code.google.com/p/chromium/issues/detail?id=350379#c4

I'll add this feature soon, possibly today.

**Comment by musically-ut** [comment]
Version `1.1.0` of the plugin fixes the issue; the settings page has relevant instructions. 

If it works for you, please close this issue. :)

**Comment by Kikju** [comment]
works great, thanks
