### ISSUE TITLE
Translate key names in UI and/or description

### ISSUE THREAD

**Issue by truthdoug** [musically-ut/key-ncognito#8]
I just looked this up for my own use but it might be useful for others.

On Mac keyboards, the "alt" key in javascript/key-ncognito is the mac option key. The "meta" is is the Mac command key (⌘).

In windows, the "meta" key is the windows key.

**Comment by musically-ut** [comment]
Thanks!

Indeed, I'll update the description of the Extension to include this detail. The `options` page does give out this detail, but it should indeed be clearer.

**Comment by musically-ut** [comment]
Done! Thanks!

**Comment by truthdoug** [comment]
Thanks, and thanks for a very useful extension!
